### PR TITLE
DSI | applying_statistical_concepts | Assignment 1

### PR DESCRIPTION
**Pull request by gordonmod8**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
added solutions to assignment_1.ipynb, worked through exercises 1 2 and 3
## Checklist
- [x] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by amanda-ng518 — CHANGES_REQUESTED** [review]
A1: Q2 missing alternative hypothesis statement
Also, please create separate pull request for each assignment

**Comment by gordonmod8** [comment]
Added text for alternative hypothesis to A1 Q2

**Comment by amanda-ng518** [comment]
alternative hypothesis is still missing for A1 Q2

**Comment by gordonmod8** [comment]
> alternative hypothesis is still missing for A1 Q2
Sorry you couldn't find it, the commit in question is here:
https://github.com/gordonmod8/applying_statistical_concepts/pull/1/commits/245ff4099574a0bb9b3690266cb17881c1bbb2d1

**Review by amanda-ng518 — APPROVED** [review]
A1: hypothesis statements can be clearer, refer to the solution when they are posted

**Pull request merged**
